spring:
  datasource:
    url: jdbc:mysql://localhost:3306/relations
    password: happy123
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 5000
